# Generated by Django 5.0.1 on 2024-02-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='portafolio/images/')),
            ],
        ),
    ]
