# Generated by Django 5.0.1 on 2024-02-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyectos',
            new_name='Proyecto',
        ),
    ]
